version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/cslib
    overwrite: true

permission:
  - object: /home/ubuntu/cslib
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ubuntu